
$(function() {

    // Populate using an object literal

WTF.init({

heading: [
             	"Listen to this shit: I'm gonna play a",
             	"I'm gonna be a fuckin'"
],

response: [
             	"I've done that shit already",
             	"Give me a-fucking-nother one",
             	"That sounds boring as fuck"
],

template: [
             	"@trait @race @class who is from @background and @strength but @flaw"
],

trait: [
//Positive Traits
"Accessible",
"Active",
"Adaptable",
"Admirable",
"Adventurous",
"Agreeable",
"Alert",
"Allocentric",
"Amiable",
"Anticipative",
"Appreciative",
"Articulate",
"Aspiring",
"Athletic",
"Attractive",
"Balanced",
"Benevolent",
"Brilliant",
"Calm",
"Capable",
"Captivating",
"Caring",
"Challenging",
"Charismatic",
"Charming",
"Cheerful",
"Clean",
"Clear-headed",
"Clever",
"Colorful",
"Companionly",
"Compassionate",
"Conciliatory",
"Confident",
"Conscientious",
"Considerate",
"Constant",
"Contemplative",
"Cooperative",
"Courageous",
"Courteous",
"Creative",
"Cultured",
"Curious",
"Daring",
"Debonair",
"Decent",
"Decisive",
"Dedicated",
"Deep",
"Dignified",
"Directed",
"Disciplined",
"Discreet",
"Dramatic",
"Dutiful",
"Dynamic",
"Earnest",
"Ebullient",
"Educated",
"Efficient",
"Elegant",
"Eloquent",
"Empathetic",
"Energetic",
"Enthusiastic",
"Esthetic",
"Exciting",
"Extraordinary",
"Fair",
"Faithful",
"Farsighted",
"Felicific",
"Firm",
"Flexible",
"Focused",
"Forecful",
"Forgiving",
"Forthright",
"Freethinking",
"Friendly",
"Fun-loving",
"Gallant",
"Generous",
"Gentle",
"Genuine",
"Good-natured",
"Gracious",
"Hardworking",
"Healthy",
"Hearty",
"Helpful",
"Herioc",
"High-minded",
"Honest",
"Honorable",
"Humble",
"Humorous",
"Idealistic",
"Imaginative",
"Impressive",
"Incisive",
"Incorruptible",
"Independent",
"Individualistic",
"Innovative",
"Inoffensive",
"Insightful",
"Insouciant",
"Intelligent",
"Intuitive",
"Invulnerable",
"Kind",
"Knowledge",
"Leaderly",
"Leisurely",
"Liberal",
"Logical",
"Lovable",
"Loyal",
"Lyrical",
"Magnanimous",
"Many-sided",
"Masculine (Manly)",
"Mature",
"Methodical",
"Maticulous",
"Moderate",
"Modest",
"Multi-leveled",
"Neat",
"Nonauthoritarian",
"Objective",
"Observant",
"Open",
"Optimistic",
"Orderly",
"Organized",
"Original",
"Painstaking",
"Passionate",
"Patient",
"Patriotic",
"Peaceful",
"Perceptive",
"Perfectionist",
"Personable",
"Persuasive",
"Planful",
"Playful",
"Polished",
"Popular",
"Practical",
"Precise",
"Principled",
"Profound",
"Protean",
"Protective",
"Providential",
"Prudent",
"Punctual",
"Pruposeful",
"Rational",
"Realistic",
"Reflective",
"Relaxed",
"Reliable",
"Resourceful",
"Respectful",
"Responsible",
"Responsive",
"Reverential",
"Romantic",
"Rustic",
"Sage",
"Sane",
"Scholarly",
"Scrupulous",
"Secure",
"Selfless",
"Self-critical",
"Self-defacing",
"Self-denying",
"Self-reliant",
"Self-sufficent",
"Sensitive",
"Sentimental",
"Seraphic",
"Serious",
"Sexy",
"Sharing",
"Shrewd",
"Simple",
"Skillful",
"Sober",
"Sociable",
"Solid",
"Sophisticated",
"Spontaneous",
"Sporting",
"Stable",
"Steadfast",
"Steady",
"Stoic",
"Strong",
"Studious",
"Suave",
"Subtle",
"Sweet",
"Sympathetic",
"Systematic",
"Tasteful",
"Teacherly",
"Thorough",
"Tidy",
"Tolerant",
"Tractable",
"Trusting",
"Uncomplaining",
"Understanding",
"Undogmatic",
"Unfoolable",
"Upright",
"Urbane",
"Venturesome",
"Vivacious",
"Warm",
"Well-bred",
"Well-read",
"Well-rounded",
"Winning",
"Wise",
"Witty",
"Youthful",

//Neutral Traits
"Absentminded",
"Aggressive",
"Ambitious",
"Amusing",
"Artful",
"Ascetic",
"Authoritarian",
"Big-thinking",
"Boyish",
"Breezy",
"Businesslike",
"Busy",
"Casual",
"Crebral",
"Chummy",
"Circumspect",
"Competitive",
"Complex",
"Confidential",
"Conservative",
"Contradictory",
"Crisp",
"Cute",
"Deceptive",
"Determined",
"Dominating",
"Dreamy",
"Driving",
"Droll",
"Dry",
"Earthy",
"Effeminate",
"Emotional",
"Enigmatic",
"Experimental",
"Familial",
"Folksy",
"Formal",
"Freewheeling",
"Frugal",
"Glamorous",
"Guileless",
"High-spirited",
"Huried",
"Hypnotic",
"Iconoclastic",
"Idiosyncratic",
"Impassive",
"Impersonal",
"Impressionable",
"Intense",
"Invisible",
"Irreligious",
"Irreverent",
"Maternal",
"Mellow",
"Modern",
"Moralistic",
"Mystical",
"Neutral",
"Noncommittal",
"Noncompetitive",
"Obedient",
"Old-fashined",
"Ordinary",
"Outspoken",
"Paternalistic",
"Physical",
"Placid",
"Political",
"Predictable",
"Preoccupied",
"Private",
"Progressive",
"Proud",
"Pure",
"Questioning",
"Quiet",
"Religious",
"Reserved",
"Restrained",
"Retiring",
"Sarcastic",
"Self-conscious",
"Sensual",
"Skeptical",
"Smooth",
"Soft",
"Solemn",
"Solitary",
"Stern",
"Stolid",
"Strict",
"Stubborn",
"Stylish",
"Subjective",
"Surprising",
"Soft",
"Tough",
"Unaggressive",
"Unambitious",
"Unceremonious",
"Unchanging",
"Undemanding",
"Unfathomable",
"Unhurried",
"Uninhibited",
"Unpatriotic",
"Unpredicatable",
"Unreligious",
"Unsentimental",
"Whimsical",

//Negative Traits
"Abrasive",
"Abrupt",
"Agonizing",
"Aimless",
"Airy",
"Aloof",
"Amoral",
"Angry",
"Anxious",
"Apathetic",
"Arbitrary",
"Argumentative",
"Arrogantt",
"Artificial",
"Asocial",
"Assertive",
"Astigmatic",
"Barbaric",
"Bewildered",
"Bizarre",
"Bland",
"Blunt",
"Biosterous",
"Brittle",
"Brutal",
"Calculating",
"Callous",
"Cantakerous",
"Careless",
"Cautious",
"Charmless",
"Childish",
"Clumsy",
"Coarse",
"Cold",
"Colorless",
"Complacent",
"Complaintive",
"Compulsive",
"Conceited",
"Condemnatory",
"Conformist",
"Confused",
"Contemptible",
"Conventional",
"Cowardly",
"Crafty",
"Crass",
"Crazy",
"Criminal",
"Critical",
"Crude",
"Cruel",
"Cynical",
"Decadent",
"Deceitful",
"Delicate",
"Demanding",
"Dependent",
"Desperate",
"Destructive",
"Devious",
"Difficult",
"Dirty",
"Disconcerting",
"Discontented",
"Discouraging",
"Discourteous",
"Dishonest",
"Disloyal",
"Disobedient",
"Disorderly",
"Disorganized",
"Disputatious",
"Disrespectful",
"Disruptive",
"Dissolute",
"Dissonant",
"Distractible",
"Disturbing",
"Dogmatic",
"Domineering",
"Dull",
"Easily Discouraged",
"Egocentric",
"Enervated",
"Envious",
"Erratic",
"Escapist",
"Excitable",
"Expedient",
"Extravagant",
"Extreme",
"Faithless",
"Fanatical",
"Fanciful",
"Fatalistic",
"Fawning",
"Fearful",
"Fickle",
"Fiery",
"Fixed",
"Flamboyant",
"Foolish",
"Forgetful",
"Fraudulent",
"Frightening",
"Frivolous",
"Gloomy",
"Graceless",
"Grand",
"Greedy",
"Grim",
"Gullible",
"Hateful",
"Haughty",
"Hedonistic",
"Hesitant",
"Hidebound",
"High-handed",
"Hostile",
"Ignorant",
"Imitative",
"Impatient",
"Impractical",
"Imprudent",
"Impulsive",
"Inconsiderate",
"Incurious",
"Indecisive",
"Indulgent",
"Inert",
"Inhibited",
"Insecure",
"Insensitive",
"Insincere",
"Insulting",
"Intolerant",
"Irascible",
"Irrational",
"Irresponsible",
"Irritable",
"Lazy",
"Libidinous",
"Loquacious",
"Malicious",
"Mannered",
"Mannerless",
"Mawkish",
"Mealymouthed",
"Mechanical",
"Meddlesome",
"Melancholic",
"Meretricious",
"Messy",
"Miserable",
"Miserly",
"Misguided",
"Mistaken",
"Money-minded",
"Monstrous",
"Moody",
"Morbid",
"Muddle-headed",
"Naive",
"Narcissistic",
"Narrow",
"Narrow-minded",
"Natty",
"Negativistic",
"Neglectful",
"Neurotic",
"Nihilistic",
"Obnoxious",
"Obsessive",
"Obvious",
"Odd",
"Offhand",
"One-dimensional",
"One-sided",
"Opinionated",
"Opportunistic",
"Oppressed",
"Outrageous",
"Overimaginative",
"Paranoid",
"Passive",
"Pedantic",
"Perverse",
"Petty",
"Pharissical",
"Phlegmatic",
"Plodding",
"Pompous",
"Possessive",
"Power-hungry",
"Predatory",
"Prejudiced",
"Presumptuous",
"Pretentious",
"Prim",
"Procrastinating",
"Profligate",
"Provocative",
"Pugnacious",
"Puritanical",
"Quirky",
"Reactionary",
"Reactive",
"Regimental",
"Regretful",
"Repentant",
"Repressed",
"Resentful",
"Ridiculous",
"Rigid",
"Ritualistic",
"Rowdy",
"Ruined",
"Sadistic",
"Sanctimonious",
"Scheming",
"Scornful",
"Secretive",
"Sedentary",
"Selfish",
"Self-indulgent",
"Shallow",
"Shortsighted",
"Shy",
"Silly",
"Single-minded",
"Sloppy",
"Slow",
"Sly",
"Small-thinking",
"Softheaded",
"Sordid",
"Steely",
"Stiff",
"Strong-willed",
"Stupid",
"Submissive",
"Superficial",
"Superstitious",
"Suspicious",
"Tactless",
"Tasteless",
"Tense",
"Thievish",
"Thoughtless",
"Timid",
"Transparent",
"Treacherous",
"Trendy",
"Troublesome",
"Unappreciative",
"Uncaring",
"Uncharitable",
"Unconvincing",
"Uncooperative",
"Uncreative",
"Uncritical",
"Unctuous",
"Undisciplined",
"Unfriendly",
"Ungrateful",
"Unhealthy",
"Unimaginative",
"Unimpressive",
"Unlovable",
"Unpolished",
"Unprincipled",
"Unrealistic",
"Unreflective",
"Unreliable",
"Unrestrained",
"Unself-critical",
"Unstable",
"Vacuous",
"Vague",
"Venal",
"Venomous",
"Vindictive",
"Vulnerable",
"Weak",
"Weak-willed",
"Well-meaning",
"Willful",
"Wishful",
"Zany"
],

race: [
"Human",
"Tiefling",
"Dragonborn",
"Dwarf",
"Elf",
"Halfling",
"Half-Elf",
"Half-Orc",
"Gnome",
"Goliath",
"Tortle",
"Leonin",
"Satyr",
"Owlin",
"Arakockra",
"Aasimar",
"Air Genasi",
"Bugbear",
"Centaur",
"Changeling",
"Deep Gnome",
"Duergar",
"Earth Genasi",
"Eladrin",
"Fairy",
"Firbolg",
"Fire Genasi",
"Githyanki",
"Githzerai",
"Goblin",
"Goliath",
"Harengon",
"Hobgoblin",
"Kenku",
"Kobold",
"Lizardfolk",
"Minotaur",
"Orc",
"Sea Elf",
"Shadar-kai",
"Shifter",
"Tabaxi",
"Triton",
"Water Genasi",
"Yuan-ti",
"Kalashtar",
"Warforged",
"Astral Elf",
"Autognome",
"Giff",
"Hadozee",
"Plasmoid",
"Thri-kreen",
"Loxodon",
"Simic Hybrid",
"Vedalken",
"Verdan",
"Locathah",
"Grung"
],

class: [
"Path of the Berserker Barbarian",
"Path of the Totem Warrior Barbarian",
"College of Lore Bard",
"College of Valor Bard",
"Knowledge Domain Cleric",
"Life Domain Cleric",
"Nature Domain Cleric",
"Tempest Domain Cleric",
"Trickery Domain Cleric",
"War Domain Cleric",
"Circle of the Land Druid",
"Circle of the Moon Druid",
"Champion Fighter",
"Battle Master Fighter",
"Eldritch Knight Fighter",
"Way of the Open Hand Monk",
"Way of Shadow Monk",
"Way of the Four Elements Monk",
"Oath of Devotion Paladin",
"Oath of the Ancients Paladin",
"Oath of Vengeance Paladin",
"Hunter Ranger",
"Beast Master Ranger",
"Thief Rogue",
"Assassin Rogue",
"Arcane Trickster Rogue",
"Draconic Bloodline Sorcerer",
"Wild Magic Sorcerer",
"Archfey Warlock",
"Fiend Warlock",
"Great Old One Warlock",
"School of Abjuration Wizard",
"School of Conjuration Wizard",
"School of Divination Wizard",
"School of Enchantment Wizard",
"School of Evocation Wizard",
"School of Illusion Wizard",
"School of Necromancy Wizard",
"School of Transmutation Wizard",
"Death Domain Cleric",
"Oathbreaker Paladin",
"Path of the Battlerager Barbarian",
"Arcana Domain Cleric",
"Purple Dragon Knight Fighter (Banneret)",
"Way of the Long Death Monk",
"Way of the Sun Soul Monk",
"Oath of the Crown Paladin",
"Swashbuckler Rogue",
"Storm Sorcery Sorcerer",
"Undying Warlock",
"Bladesinging Wizard",
"Pyromancer Sorcerer",
"Solidarity Domain Cleric",
"Strength Domain Cleric",
"Ambition Domain Cleric",
"Zeal Domain Cleric",
"Path of the Ancestral Guardian Barbarian",
"Path of the Storm Herald Barbarian",
"Path of the Zealot Barbarian",
"College of Swords Bard",
"College of Whispers Bard",
"Forge Domain Cleric",
"Circle of Dreams Druid",
"Circle of the Shepherd Druid",
"Cavalier Fighter",
"Samurai Fighter",
"Way of the Drunken Master Monk",
"Way of the Kensei Monk",
"Oath of Conquest Paladin",
"Oath of Redemption Paladin",
"Gloom Stalker Ranger",
"Horizon Walker Ranger",
"Monster Slayer Ranger",
"Inquisitive Rogue",
"Scout Rogue",
"Shadow Magic Sorcerer",
"Celestial Warlock",
"Hexblade Warlock",
"War Magic Wizard",
"Order Domain Cleric",
"Circle of Spores Druid",
"Alchemist Artificer",
"Artillerist Artificer",
"Battle Smith Artificer",
"Echo Knight Fighter",
"Graviturgy Magic Wizard",
"College of Eloquence Bard",
"Oath of Glory Paladin",
"Armorer Artificer",
"Path of the Beast Barbarian",
"Path of Wild Magic Barbarian",
"Peace Domain Cleric",
"Twilight Domain Cleric",
"Psi Warrior Fighter",
"Rune Knight Fighter",
"Way of Mercy Monk",
"Fey Wanderer Paladin",
"Swarmkeeper Ranger",
"Phantom Rogue",
"Aberrant Mind Sorcerer",
"Fathomless Warlock",
"Genie Warlock",
"Order of Scribes Wizard"
],

background: [
"the wealthy part of a beggar's city",
"the ass end of Nowhere",
"a now collapsed empire",
"a city that never sleeps",
"a travelling circus (the freak show in particular)",
"a hole in the ground literally ",
"an upstanding family who are ruled by a not so upstanding lord",
"somewhere really far away from here",
"an ancient mountain city",
"reclaimed ruins of a forgotten people",
"an underwater city",
"a floating city",
"a city where everyone breaks out in song and dance all the time",
"a tiny village",
"the smallest mountain in the world",
"the forest of sadness",
"the city sewers",
"the gutter",
"a large family",
"a orphanage workhouse",
"a slave owning city",
"a town that only ever bartered for goods",
"a super religious upbringing",
"a mid-level cult",
"a cavern without echoes",
"a commune",
"the wet desert",
"an unchartable island",
"a small family farm",
"a village without a tavern",
"the slave fighting pits",
"a company of sellswords",
"an underground network of dragon caves",
"a mercenary company",
"a nocturnal town",
"a city that never slept",
"a royal lineage",
"a carnival freak show",
"an impure bloodline",
"the petrified wood",
"a strict monastery",
"a local street gang",
"the now dry swamp",
"a ruined city",
"a haunted castle",
"the best library in the city",
"a bustling city",
"a maximum security prison",
"a floating city",
"an underground city",
"a theatre company",
"the guard's academy",
"a small town tavern",
"the grave diggers union",
"the royal bank",
"a haberdashery",
"the city post office",
"a travelling band",
"a fishing village",
"a boarding school for the children of middle-class wizards",
"the base of a volcano",
"an illusory forest",
"a forgotten elven monastery",
"the pirate infested isles",
"an unchartable island",
"an asylum",
"a fallen kingdom",
"the inner city slums",
"an underwater monastery",
"a mining town",
"a high-class brothel",
"a nomad circus",
"a tourist town in the mountains",
"the high-plains desert",
"an oasis village",
"the worst brothel in town",
"the freelands",
"a children's workhouse",
"the tundra",
"the nice part of a bad town",
"a peaceful coastal town ",
"the wilds",
"a pompous wizard school",
"a small remote village",
"an ancient monastery",
"a very tiny province",
"a silk & spices trade galley",
"the tower of bones",
"a string of terrible places to live",
"a notorious dungeon",
"the wild wood",
"the hold of a slave ship",
"the slums of a port city",
"a laid back beach town",
"a place only they can pronounce",
"an extremist temple",
"the rat catchers guild",
"a sheltered upbringing",
"a sunken city",
"the dry lands",
"the salt flats",
"a city in the shifting sands",
"the most vile of swamps",
"a tropical paradise",
"a gnome run orphanage",
"a recently erupted volcano village",
"Waterdeep",
"a small family bakery",
"a small town where nothing ever happened",
"an underground military stronghold",
"a town of Outlaws",
"a war-torn city",
"a plague ridden city",
"a poor dairy farm",
"the local tavern",
"the northern icelands",
"the dusty mountains",
"an isolated monastery ",
"Briarwood Castle",
"the endless cornfields ",
"the Gladiator Arena",
"an affluent upbringing",
"a prison colony",
"a backwater village",
"from a city deep under the mountains",
"the northern wastelands",
"a local brewery",
"a small town wizarding school",
"a secluded forest village",
"a desert town hidden inside a sandstorm",
"a wealthy vineyard",
"a frozen jungle",
"the city slums",
"A floating shanty town",
"A cliff-side village",
"a rundown adventuring tavern",
"a moving island",
"a cursed village",
"the Ruined Sea",
"a quiet woodland hut",
"the sea of sand",
"the citadel",
"an island long thought to be uninhabited",
"the long abandoned mines",
"a small town on the border",
"a broken home",
"a thriving seaport town",
"a destroyed city",
"the North Plains",
"the iceberg sea",
"the Valley of the Giants",
"the badlands",
"the wilderness",
"a quaint little village on a hill",
"a haunted forest",
"a conquered city",
"the lizard infested marshlands",
"the kitchens of the local barracks",
"Black Rock Beach",
"an internment camp",
"a small farm in the grasslands",
"an engineer's guild",
"Thornwood",
"the treeless forest",
"the Dank Hollows",
"a bustling underground kingdom",
"an underwater city once dry by a magical force field",
"the strongest family heritage line in the land",
"the royal catacombs",
"a fake leper colony hiding a secret",
"a halfway house",
"the city of lights",
"the City of Ten Thousand Flags",
"the enchanted forest",
"a slave market",
"a city no one else has ever heard of",
"The mean uncobbled streets of the city",
"the dungeon inspector's guild (local #422)",
"Lady Marigold's Dance Academy",
"a camp of army followers",
"a doomed dwarven fortress",
"a city with towers that rival the clouds",
"the wetlands",
"A destitute plantation",
"the royal court",
"A foggy peninsula",
"A secret brawler's guild",
"a hastily erected tent city",
"an aristocratic family",
"the Parliament of Beggars",
"a enchanted forest logging company",
"the scorched plains",
"the boneyard",
"the iron mountain range",
"the deep wood",
"the vast wastes",
"the black dungeon",
"a powerful trading town",
"the poor surroundings of the capital city",
"a low ceilinged castle",
"a line of fallen royalty",
"a boarding school",
"Black Oak",
"the white halls of the north",
"a village without children",
"the Wayferer Foothills",
"a deserted island",
"the shifting desert",
"the shade forests",
"a sunken city",
"a rural construction company",
"the assassins guild",
"the black citadel",
"an abandoned fortress",
"an island that can't be reached by boat",
"the endless wastes",
"a frozen wasteland",
"a free thinkers commune",
"a broken home",
"a sleepy harbour town",
"The shattered mountain range",
"the forked islands",
"a disgraced family of knights",
"the city watch",
"a refugee camp for war orphans",
"a complex bureaucratic society",
"a large desert metropolis",
"a dysfunctional marriage",
"a poorly run orphanage",
"a bustling city market",
"a dilapidated mansion",
"a young offenders institute",
"the Forest of Faces",
"the improbable peaks",
"the sealed city",
"the 'class act' travelling circus",
"a run down tavern",
"the Underdark",
"a man made desert",
"a slave caravan",
"the fey wilds",
"a high end gambling house",
"a drought-stricken farm",
"a now impoverished noble family",
"the quality control for potion brewing association",
"a town where orcs are bought and sold as slaves",
"a secret order of monks",
"the imperial army"
],


strength: [
"really knows how to dance",
"puts in more effort than anyone",
"cares more about others than themself",
"is a real free spirit",
"only targets those who can afford it",
"refuses to do the same con twice",
"believes friendship lasts forever",
"is determined to make something of themselves",
"will do whatever it takes to get rich",
"is loyal to their friends only, everyone else can go to hell",
"is absolutely shredded, and takes pride in it",
"makes the world better with every performance",
"doesn't pretend to be something their not",
"is only in this for the money",
"believes emotions will only cloud their judgement",
"is reluctant to accept any help",
"wont let anyone tell them what to do",
"seeks glory in battle, even at the cost of death",
"believes knowledge is the path to power",
"is searching for the knowledge of true immortality",
"is planning to retire next year",
"is really good at bribing officials",
"is searching for the knowledge of true immortality",
"is planning to retire next year",
"is really good at bribing officials",
"has always wanted to open their own tavern",
"always wanted to learn magic but struggled with it",
"studied interior dungeon design",
"is writing an autobiography",
"was brought up to be a librarian",
"always romanticised adventure",
"meditates before dawn",
"always wakes up on the right side of the bed",
"always keeps their promises",
"is trying to get out of the adventuring business to settle down",
"takes great delight in identifying new beetle species",
"was a weapons instructor for the city militia",
"aims to learn every language in the land",
"once served as a court jester",
"already made and lost a fortune",
"has a poem for all occasions",
"was drafted into the army at fourteen",
"was apprenticed to a failed alchemist",
"is writing an epic poem about the party's adventure",
"really knows how to party",
"loves to haggle",
"came out of retirement for this adventure",
"just wants their money back",
"always wanted to be an artist",
"rejected a foreign prince's marriage proposal",
"ran away at the age of eleven",
"won a duel they were supposed to lose out of sheer luck",
"seems to know everyone",
"secretly became an adventurer to impress a love interest",
"searches endlessly for their kidnapped child",
"is searching for the perfect culinary dish",
"is just trying to get by",
"is trying to avoid a prophecy",
"wants to clear their name",
"once survived a boiling cauldron",
"has cheated death more times than they deserved",
"adds a notch to their sword every night",
"wants to prove they're no longer that goofy kid",
"has gotten away with murder",
"is searching for a rare fertility herb",
"wants to one day own their own ship ",
"is the last of an ancient bloodline",
"is the twin of the local monarch",
"always thinks outside the box",
"carries a cryptic treasure map they won in a tavern bet",
"believes they have a claim to the throne",
"seeks to end a family feud",
"sold everything they own to attend an adventurer academy",
"fights for species equality",
"is trying to dodge the draft",
"was beaten and imprisoned for their religious beliefs",
"started a rebellion in the northern mountains",
"wants to become a famous singer",
"was, until recently, employed to run a dungeon",
"always looks their best",
"used to work as a tavern bouncer",
"tries to be a friend to everyone",
"is a former bare knuckle boxer",
"can drink with the best of them",
"wants to eventually be king",
"is avoiding an ex-lover",
"tries to find meaning in everything"
],

flaw: [
"is all show, no go.",
"is a candidate for optorectomy. (Disconnection of optic nerve from rectum, to repair a crappy outlook on life.)",
"is usually a day late and a dollar short.",
"has a great deal of pride, but very little to be proud of.",
"is a pacifist out of necessity.",
"is only live today only because it's illegal to kill them.",
"has all the personality of a bowl of oatmeal.",
"is always in the right place, but at the wrong time. (plagued by inconvenience)",
"always needs to have jokes explained.",
"is always sharpening their sleeping skills.",
"has an ego like a black hole.",
"is as focused as a fart.",
"is as funny as a fire in a children's home.",
"is as popular as a French kiss at a family reunion.",
"is as honest as a politician.",
"is as worn out as a cucumber in a convent.",
"is as strong as an ox and as dumb as two.",
"they are better at sex than anyone; now all they need is a partner.",
"has a prosthetic limb and is kind of pissed about it.",
"has no idea how magic works.",
"couldn't fight their way out of a wet paper bag.",
"couldn't pour water out of a boot with instructions on the heel.",
"lost most their wealth gambling and is convinced that guy across the table was cheating.",
"is hell-bent on proving they are the best at what they do.",
"they can't hold water in a bucket (can't keep a secret).",
"is as busy as a one-legged man in an ass-kicking contest.",
"is as confused as a baby in a topless bar.",
"consumes hard drugs as vitamins.",
"is as cunning as a dodo bird.",
"they're either the good twin or the evil one, hard to say.",
"is as focused like a 12 gauge shotgun.",
"for those who never forget a face, theirs is an exception.",
"gives a lot of bull for somebody what ain't got no cattle.",
"is God's favorite target for lightning strikes.",
"has habits only explainable if they were raised by wolves.",
"has plenty of talent and vision, just doesn't give a damn.",
"has the attention span of an overripe grapefruit.",
"has the keen awareness of an ostrich in hiding.",
"they have the wisdom of youth, and the energy of old age.",
"they have two left feet.",
"they're really into themself... their head is up their ass.",
"their face is a threat to mirrors everywhere.",
"their personal problems can only be solved using high explosives.",
"is all bark, no bite.",
"doesn't believe in magic ever",
"hates wearing their glasses",
"finds it impossible to speak to girls",
"has a huge debt to pay back",
"was raised by ghosts",
"suffers from claustrophobia",
"is really (I MEAN REALLY) afraid of the dark",
"makes inappropriate jokes at the worst times",
"is afraid of heights",
"doesn't understand the concept of politeness",
"always alliterates their anecdotes",
"has a bad gambling problem",
"was told they'll never be good enough",
"wants everyone to like them",
"never takes their armour off just in case",
"always needs to be the centre of attention",
"has no other family but the party",
"was left out of their father's will",
"is downright racist towards living skeletons",
"believes they're a demi god but hasn't figured out who their father is yet",
"has serious daddy issues",
"has a drinking problem",
"is completely colour blind",
"failed out of every guild going",
"saw their whole family consumed by a gelatinous cube",
"gets nervous speaking in front of crowds",
"is afraid of sharp edges",
"doesn't have a reflection",
"suffers from nosebleeds",
"is uncomfortable around old people (they smell like death)",
"can't swim",
"grew up in a graveyard",
"is afraid of fire",
"hates music",
"grew up fat",
"distrusts all authority",
"mistrusts anyone smaller than them",
"hates the monarchy",
"is afraid of dogs",
"was once rescued by wolves",
"has anger problems",
"can't read",
"deserted the army",
"is responsible for their sister's death",
"is certain their days are numbered",
"always takes first watch",
"can't silence the voices",
"constantly watches their back",
"always refers to inanimate objects as 'she'",
"is a recovering cannibal",
"wants to be famous no matter what",
"believes trees can speak to them and them alone",
"has serious body image problems",
"is a recovering gambling addict",
"can't stand the sight of blood",
"is afraid the rest of the party will kill them if they try to leave",
"would rather kill you than make eye contact",
"was kidnapped by cultists",
"has twenty-seven siblings to provide for",
"ran afoul of the goblin mob",
"has nothing left to lose",
"doesn't know their own strength",
"has had it up to here with everyone's crap",
"is red-green colorblind",
"carries the skull of their best friend",
"has a serious weapons fetish",
"has taken a vow of silence",
"has really bad hay fever",
"doesn't believe in hygiene",
"is being hunted by a terrible monster",
"is dying of a plague and searching for a cure",
"lost their family in a dragon attack",
"is forever picking fights to 'win back honour'",
"can't stand silence",
"lost minor appendages due to their gambling addiction",
"is absolutely astonished by jugglers",
"can't sleep indoors",
"only sleeps with the lights on",
"hates to be clean",
"drunkenly swore a blood oath and forgot what for",
"doesn't perceive gender",
"realised the importance of literacy far too late in life",
"bangs on about their genealogy to everyone",
"keeps a blacklist",
"lost their shadow in a bet",
"gets easily attached to people",
"finds armour too restricting",
"has no sense of smell",
"insists they are the reincarnation of a legendary warrior",
"refuses to bathe",
"loved lost and never loved again",
"is lactose intolerant",
"prefers to fight drunk",
"thinks they can read the future but consistently gets it wrong",
"killed their brother in a duel over their inheritance",
"is cursed to speak in sentences of exactly ten words",
"was raised as a hostage by their father's enemies",
"has an irrational fear of cats",
"is completely and utterly tone-deaf",
"is running from a marriage arranged by their parents",
"knows seven dangerous secrets",
"has a debilitating fear of wide open spaces",
"always speaks in the third person",
"is manically obsessed with etiquette",
"is secretly fond of embroidery",
"is a compulsive liar",
"hates the written word",
"likes to settle arguments with headbutting contests",
"has an outstanding warrant for their arrest",
"is pretty tight fisted with their gold",
"is the only surviving member of their previous adventure party",
"was disowned by their family",
"names every piece of their gear",
"is a complete exhibitionist",
"accidentally torched the local temple and is now cursed by its god",
"has been exiled twice under different names",
"constantly places themselves in danger just to prove a point",
"has a pretty selective memory",
"has accepted death as an inevitability",
"has been on the run for over three years",
"is terrified of rats",
"believes the undead should be given a second chance",
"was forced to watch their families execution",
"can't stand children",
"worries some of their memories have been tampered with",
"hates to be touched",
"lost their sense of smell in a bar fight",
"likes to speak in rhyme",
"can't seem to hold their liquor",
"was petrified for over two hundred years",
"unwittingly misuses words all the bloody time",
"acts shallow but only to hide their insecurities",
"makes all minor decisions by flipping a coin",
"had their lost legs replaced with enchanted wood",
"is haunted by the ghost of their father",
"was exiled by their brother the king",
"always gives the good news first",
"hates riding horses",
"left their home in disgrace",
"doesn't understand sarcasm",
"suffers from night terrors",
"never passes up a chance to say 'I told you so.'",
"was framed for the murder of a famous and well-loved innkeeper",
"always cuts to the chase",
"always gives the bad news first",
"is on the run after having an affair with a noble's daughter",
"has a twin that constantly impersonates them",
"hasn't been quite right since the accident",
"hasn't accomplished anything in their short life yet",
"is trapped in a Faustian bargain",
"lost their marbles a long time ago",
"has a burning hatred for pirates",
"owes money to the wrong people",
"believes in an eye for an eye",
"never turns the other cheek",
"in hindsight shouldn't have had the treasure map tattooed on themselves",
"has a regular sleepwalking issue",
"was cut from their dead mother's womb",
"was jailed for a crime they didn't commit",
"is posing as someone else",
"was expelled from the royal guards",
"is the last of the king's bastard children",
"has never been kissed",
"suffers from crippling stage-fright",
"suffers from a recurring nightmare",
"needs to earn the trust of a hated duke",
"loots every kill but leaves enough to pay for their burial",
"woke up in a bar with no memory and a sealed letter",
"is haunted by the ghosts of their forefathers",
"doesn't have time for all this prophecy bullshit",
"is dealing with a midlife crisis",
"has delusions of grandeur",
"believes plate armour is just a sign of being posh and over privileged",
"failed to protect the royal family",
"likes to settle arguments with an arm wrestle",
"never returned anything they borrowed",
"had their nose cut off in a duel",
"believes dungeon crawling is just breaking and entering",
"bribed a nobleman to help them smuggle slaves out of a tyrannical kingdom",
"was born in a different body",
"suffers from vertigo",
"lost two fingers in a training accident",
"is tracking down the treasure their father died trying to find",
"carries a charmed locket that they can't open",
"is getting too old for all this",
"no longer dreams",
"has a bad habit of making 'funny' quips after every kill",
"has wooden teeth after the incident with the mace",
"carries the scars of an attempted suicide",
"hates being made to wait",
"keeps getting mistaken for a famous knight",
"lost their best friend in an ambush",
"is currently on probation for drunk and disorderly behaviour",
"is haunted by the ghosts of those they kill",
"was badly burnt by a sorcerer",
"was written out of their family will",
"is in way too deep with the wrong sort of people",
"exaggerates everything they talk about",
"has no concept of personal space",
"never got the proper training",
"is in so far over their head that they can't help but laugh",
"can only whisper after an attempted hanging",
"is quick to take credit and assign blame",
"refuses to admit they're past their prime",
"has never had their hair cut",
"only has two more years before a demon comes back to claim their soul",
"only became an adventurer after losing a bet",
"is wanted for a reward",
"wears a mysterious necklace that constantly brings them out in a rash",
"parties hard way too hard.",
"isn't technically alive anymore",
"is convinced they're always being left out",
"doesn't speak a word of common"
]

});
});